#!/bin/sh

export MANROFFOPT="-c";
export LESS="-R";
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink
export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;33m'    # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

yazi_wrapper() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}

zellij_wrapper() {
    zellij "$@"
    # remove all the temp cache
    find "${XDG_CACHE_HOME:-$HOME/.cache}/zellij" \
        -maxdepth 1 -type d \
        -name "????????-????-????-????-????????????" \
        -exec rm -rf {} +
}

passgen() {
    read -s MSG
    echo -n "$MSG" | openssl dgst -sha256 -binary | base64 | head -c 12 | awk '{print $0"K@!"}'
}

cheat() {
    curl -s "cheat.sh/$1" | {
        if command -v bat 2>&1 > /dev/null; then
            bat -p
        else
            less
        fi
    }
}
