#!/bin/sh

yazi_wrapper() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}

zellij_wrapper() {
    zellij "$@"
    # remove all the temp cache
    find "${XDG_CACHE_HOME:-$HOME/.cache}/zellij" \
        -maxdepth 1 -type d \
        -name "????????-????-????-????-????????????" \
        -exec rm -rf {} +
}

passgen() {
    read -s MSG
    echo -n "$MSG" | openssl dgst -sha256 -binary | base64 | head -c 12 | awk '{print $0"K@!"}'
}

cheat() {
    curl -s "cheat.sh/$1" | {
        if command -v bat 2>&1 > /dev/null; then
            bat -p
        else
            less
        fi
    }
}
